"""Draft a cover letter from your profile and the posting.

Template-based, not generated by a model. Three reasons: it costs nothing and
needs no key, it is deterministic so you can read it once and trust the shape
for ever, and a short specific letter that names the overlapping skills beats
a fluent generic one. You are expected to edit it — it opens in your editor.
"""

from __future__ import annotations

import textwrap

from .match import Match
from .models import Job
from .resume import Profile

# Skills are stored lowercase for matching; a letter has to spell them the way
# the industry does.
_PRETTY = {
    "rest": "REST APIs", "sql": "SQL", "jwt": "JWT", "aws": "AWS", "gcp": "GCP",
    "nlp": "NLP", "ci/cd": "CI/CD", "html": "HTML", "css": "CSS", "php": "PHP",
    "llm": "LLMs", "etl": "ETL", "node": "Node.js", "vue": "Vue.js",
    "javascript": "JavaScript", "typescript": "TypeScript", "mongodb": "MongoDB",
    "postgres": "PostgreSQL", "sqlite": "SQLite", "sqlalchemy": "SQLAlchemy",
    "mysql": "MySQL", "graphql": "GraphQL", "fastapi": "FastAPI",
    "nextjs": "Next.js", "scikit-learn": "scikit-learn", "pytorch": "PyTorch",
    "tensorflow": "TensorFlow", "numpy": "NumPy", "kubernetes": "Kubernetes",
    "rabbitmq": "RabbitMQ", "c++": "C++", "c#": "C#", "machine learning":
    "machine learning", "deep learning": "deep learning",
    "computer vision": "computer vision", "microservices": "microservices",
}


def _pretty(skill: str) -> str:
    return _PRETTY.get(skill, skill.capitalize())


def draft(job: Job, profile: Profile, match: Match) -> str:
    full = " ".join(w.capitalize() for w in (profile.name or "").split())
    overlap = [_pretty(x) for x in match.overlap[:5]]

    if overlap:
        skills = ", ".join(overlap[:-1]) + (" and " + overlap[-1] if len(overlap) > 1
                                            else overlap[0] if overlap else "")
        skill_line = (
            f"Your posting asks for {skills}, which is the stack I work in "
            f"day to day."
        )
    else:
        skill_line = (
            "I build full-stack web applications end to end, from the database "
            "through the API to the interface."
        )

    role = profile.headline or "Software Developer"
    where = f" in {job.location.split(',')[0].strip()}" if job.location else ""

    body = f"""\
Dear Hiring Team,

I am writing about the {job.title} role at {job.company}{where}.

I am a {role} currently working at my first full-time role, where I contribute
to Python backend services handling data versioning, scheduling and a pipeline
that moves data from collection through to publishing. {skill_line}

Alongside that I have shipped several projects end to end — a placement
management platform with role-based access and background jobs on Celery and
Redis, and a hospital management system deployed to production. I have solved
over 200 data structures and algorithms problems and won a few hackathons,
which is mostly to say I enjoy building things under a deadline.

I would welcome the chance to talk about how I could contribute to your team.

Thank you for your time,
{full}
{profile.email}
{profile.phone}"""

    return textwrap.dedent(body)
